### ISSUE TITLE
[Bard the Bot]

### ISSUE THREAD

**Issue by Vincenzo-Petrolo** [MozillaItalia/DeepSpeech-Contest#1]
* Referente: @magdharion (username telegram)
* Progetto: https://github.com/Vincenzo-Petrolo/Bard-the-bot
* Breve descrizione: Bot helper per discord, usato nelle sessioni di Dungeons & Dragons per riprodurre musica d'ambiente in base alle descrizioni del Dungeon Master.
* Link video: https://youtu.be/WKSCtr7Ag5w
* Esperienze in progetti FOSS: Sviluppo di app android  open source(MQTT Joystick Controller) , filtro di immagini open source con python (Image Sorter).

**Comment by dag7dev** [comment]
Mica è pronto il video?

**Comment by Vincenzo-Petrolo** [comment]
Il bot è ancora in fase di sviluppo, mi dispiace

**Comment by Vincenzo-Petrolo** [comment]
Il bot è uscito dalla fase di sviluppo ed è nella versione di prima release.
Nei prossimi giorni registreremo un video dimostrazione. Manderò una notifca quando sarà pronto :+1:

**Comment by Sav22999** [comment]
@Vincenzo-Petrolo attendiamo il video con ansia 😄

**Comment by Vincenzo-Petrolo** [comment]
Il video è stato caricato, il link è nel primo messaggio della issue.
Spero vi piaccia :smiley:

**Comment by Sav22999** [comment]
L'idea sembra molto originale e sicuramente interessante 👍 (anche se non video non mi sembra ci sia un'effettiva dimostrazione del funzionamento del bot)

**Comment by Vincenzo-Petrolo** [comment]
Magari non si capisce, ma c'è nella sezione "Sessione di gioco", che è una clip estrapolata da una vera sessione dove si sente appunto il bot che mette musica di sottofondo.
Effettivamente l'audio del bot non è molto alto perchè lo uso come musica ambient, e quindi proprio per quello non devo ascoltare lui ma i giocatori. Spero che ciò non comprometta la valutazione...

**Comment by Sav22999** [comment]
Ma no, figurati. Il video è solo una demo, non il progetto in sé (che come ho detto è molto interessante ;))

**Comment by Sav22999** [comment]
@Vincenzo-Petrolo Ci ho pensato solo ora, ed è semplicemente un consiglio per migliorare il tuo progetto, ma puoi assolutamente ignorarlo. Perché un aggiungi un'opzione per poter cambiare il volume dell'audio di sottofondo?
Immaginando che il progetto potrebbe essere utilizzato da varie persone e con gusti differenti, magari una persona gradirebbe un volume maggiore, un'altra più basso, e così via 😄

**Comment by Vincenzo-Petrolo** [comment]
Il volume è possibile cambiarlo da discord direttamente, io lo tengo intorno al 30% di quello effettivo, ma volendo si può alzare fino al 200%

8 nov 2020 15:59:08 Saverio Morelli <notifications@github.com>:

**Comment by Sav22999** [comment]
Mh, sì, vero 👍

**Comment by Sav22999** [comment]
@Vincenzo-Petrolo 

Il contest è ufficialmente finito ieri. Stiamo valutando i progetti per decretare i vincitori. Ringraziamo, comunque, indistintamente tutti per aver partecipato a questo primo contest di Mozilla Italia su DeepSpeech.
I parametri di valutazione sono i seguenti (lo comunichiamo ora per trasparenza e chiarezza): User-friendly, Estensibilità, Documentazione, Chiarezza del codice, Originalità e Valutazione soggettiva (del singolo giurato).
Quando avremo finito le valutazioni sarà resa pubblica la classifica con la media delle valutazione dei membri della giuria (ed eventualmente una breve motivazione, generale). Sarà resa disponibile anche la spiegazione di ogni singolo parametro.
