### ISSUE TITLE
[Faber-js]

### ISSUE THREAD

**Issue by nicosh** [MozillaItalia/DeepSpeech-Contest#2]
* Referente: facebook.com/nicosh
* Progetto: https://github.com/nicosh/faber-js
* Breve descrizione:  Applicazione che utilizza DS per provare ad indovinare che canzone di De andrè stai cantando o leggendo
* Link video:  https://deepspeech.czzncl.dev/ (live demo)

**Comment by dag7dev** [comment]
Puoi mica migliorare il riconoscimento? Non dipende da te vero?
![image](https://user-images.githubusercontent.com/44711271/96338159-805d5c00-108c-11eb-9a1b-2d865d134e7f.png)

Anyway, ti starro la repo! Mi piace un sacco l'idea!

**Comment by Mte90** [comment]
Il riconoscimento dipende dal modello

**Comment by nicosh** [comment]
@dag7dev grazie! come detto da @Mte90 il riconoscimento dipende per lo più dal modello, sembrerebbe anche che  utilizzare un buffer anzichè un file audio incida leggermente.

**Comment by Sav22999** [comment]
Sembra un'idea fantastica ed è anche ben fatto! (peccato che personalmente non conosco canzoni di De andrè)

**Comment by nicosh** [comment]
@Sav22999 Grazie! comunque sei sempre in tempo per rimediare :D (intendo per conoscere le canzoni).

**Comment by Sav22999** [comment]
@nicosh 

Il contest è ufficialmente finito ieri. Stiamo valutando i progetti per decretare i vincitori. Ringraziamo, comunque, indistintamente tutti per aver partecipato a questo primo contest di Mozilla Italia su DeepSpeech.
I parametri di valutazione sono i seguenti (lo comunichiamo ora per trasparenza e chiarezza): User-friendly, Estensibilità, Documentazione, Chiarezza del codice, Originalità e Valutazione soggettiva (del singolo giurato).
Quando avremo finito le valutazioni sarà resa pubblica la classifica con la media delle valutazione dei membri della giuria (ed eventualmente una breve motivazione, generale). Sarà resa disponibile anche la spiegazione di ogni singolo parametro.
