### ISSUE TITLE
[another-one-the-game]

### ISSUE THREAD

**Issue by dag7dev** [MozillaItalia/DeepSpeech-Contest#3]
* Referente: me medesimo, dag7dev, su telegram @dag7d, tutti gli altri contatti sul mio sito ufficiale
* Progetto: [another-one-the-game](https://github.com/dag7dev/another-one-the-game)
* Breve descrizione:
```
gioco ispirato a un famoso quiz televisivo.

In questo gioco viene proposto di rispondere a delle domande con una particolarita': non bisogna dare la risposta giusta bensi' quella sbagliata.

Quando apparira' la domanda sullo schermo, bisognera' rispondere ad alta voce in modo errato per andare avanti.

Il gioco finisce quando si finiscono i tentativi massimi (3) oppure quando si indovinano dieci risposte sbagliate di fila.
```
Screenshot:
![immagine](https://user-images.githubusercontent.com/44711271/98537256-49dcc080-2289-11eb-8e3a-b7675d2b8bf9.png)

* Link video: https://youtu.be/yg24QLd1X3c
* Link video (versione da terminale):  https://youtu.be/_Xzh0uLZWM4
* Esperienze in progetti FOSS: [tutto sul mio profilo mozilliano](https://people.mozilla.org/p/dag7) o qui su github

**Comment by Sav22999** [comment]
@dag7dev aspettiamo il video demo con ansia!!

**Comment by dag7dev** [comment]
Ho finalmente girato un breve video dimostrativo!
È disponibile a questo indirizzo: https://youtu.be/_Xzh0uLZWM4

**Comment by Sav22999** [comment]
Video ben fatto (dimostra appieno ciò che fa il progetto).

Personalmente mi piace molto l'idea, peccato sia un po' "limitante".
La butto lì e ti do alcuni consigli:
1. dare la possibilità di modificare il tempo massimo tra domanda-risposta
2. dare la possibilità di attivare o disattivare un tempo massimo entro il quale devi aver dato tutte le risposte oppure, automaticamente, perdi
3. aggiungere una interfaccia grafica che renderebbe sicuramente più completo e migliore il progetto in sé


In ogni caso, l'idea di fondo (quella di utilizzare il modello DS) è stata soddisfatta 👍

**Comment by dag7dev** [comment]
Ottime idee, credo di condensare tutto in una semplice UI, spero di farcela entro la scadenza, grazie mille!

**Comment by dag7dev** [comment]
UI aggiunta, video aggiornato e screenshot aggiunto💪‍‍

**Comment by Sav22999** [comment]
@dag7dev 

Il contest è ufficialmente finito ieri. Stiamo valutando i progetti per decretare i vincitori. Ringraziamo, comunque, indistintamente tutti per aver partecipato a questo primo contest di Mozilla Italia su DeepSpeech.
I parametri di valutazione sono i seguenti (lo comunichiamo ora per trasparenza e chiarezza): User-friendly, Estensibilità, Documentazione, Chiarezza del codice, Originalità e Valutazione soggettiva (del singolo giurato).
Quando avremo finito le valutazioni sarà resa pubblica la classifica con la media delle valutazione dei membri della giuria (ed eventualmente una breve motivazione, generale). Sarà resa disponibile anche la spiegazione di ogni singolo parametro.

**Comment by dag7dev** [comment]
> @dag7dev 
> 
> Il contest è ufficialmente finito ieri. Stiamo valutando i progetti per decretare i vincitori. Ringraziamo, comunque, indistintamente tutti per aver partecipato a questo primo contest di Mozilla Italia su DeepSpeech.
> I parametri di valutazione sono i seguenti (lo comunichiamo ora per trasparenza e chiarezza): User-friendly, Estensibilità, Documentazione, Chiarezza del codice, Originalità e Valutazione soggettiva (del singolo giurato).
> Quando avremo finito le valutazioni sarà resa pubblica la classifica con la media delle valutazione dei membri della giuria (ed eventualmente una breve motivazione, generale). Sarà resa disponibile anche la spiegazione di ogni singolo parametro.

Cosa si intende per estensibilità? @Sav22999

**Comment by Sav22999** [comment]
"[...] Sarà resa disponibile anche la spiegazione di ogni singolo parametro."
Nella classifica troverete tutto 😉
