### ISSUE TITLE
[Android DeepSpeech-Mycroft companion app]

### ISSUE THREAD

**Issue by kamir86** [MozillaItalia/DeepSpeech-Contest#4]
* Referente: me stesso, telegram: @aboccacci
* Progetto:[Android DeepSpeech-Mycroft companion app]( https://github.com/kamir86/MycroftDeepspeechCompanionApp)
* Breve descrizione: Questa app utilizza il modello italiano per deepspeech e manda il testo riconosciuto all'assistente mycroft, funziona completamente su rete locale
* Link video: https://youtu.be/w3YCi_m3WWU
* Esperienze in progetti FOSS: Qualche skill per mycroft

**Comment by Sav22999** [comment]
@kamir86 Aspettiamo con ansia il tuo video di presentazione 😄

**Comment by kamir86** [comment]
video pubblicato, ho avuto qualche problema con il recording dell'audio durante il riconoscimento e ho dovuto appiccicarcelo sopra. 
Il telefono non registra l'audio durante il riconoscimento vocale perchè lo manda all'app che ho creato (non ho trovato nessun workaround, ma se lo conoscete fatemelo sapere che riregistro quella parte) , non essendo bravo ad equalizzare potrebbe sentirsi

**Comment by Sav22999** [comment]
@kamir86 il video mi sembra assolutamente ben fatto e dimostra appieno il progetto.
Simpatica la parte finale 😆

**Comment by kamir86** [comment]
ho dovuto modificare la skill appositamente per farla eh? :) non è in produzione sulle skill mycroft!

**Comment by Sav22999** [comment]
@kamir86 

Il contest è ufficialmente finito ieri. Stiamo valutando i progetti per decretare i vincitori. Ringraziamo, comunque, indistintamente tutti per aver partecipato a questo primo contest di Mozilla Italia su DeepSpeech.
I parametri di valutazione sono i seguenti (lo comunichiamo ora per trasparenza e chiarezza): User-friendly, Estensibilità, Documentazione, Chiarezza del codice, Originalità e Valutazione soggettiva (del singolo giurato).
Quando avremo finito le valutazioni sarà resa pubblica la classifica con la media delle valutazione dei membri della giuria (ed eventualmente una breve motivazione, generale). Sarà resa disponibile anche la spiegazione di ogni singolo parametro.
