### ISSUE TITLE
[Watson assistant from telegram with speech to text]

### ISSUE THREAD

**Issue by Anulo2** [MozillaItalia/DeepSpeech-Contest#5]
* Referente: Leonardo Canello aka _Zaizen_ @Anulo2SecondoAcc (Telegram)
* Progetto: https://gitlab.com/_Zaizen_/pecore-elettriche
* Breve descrizione: durante le ultime settimane stavo lavorando ad un progetto di scuola nel quale stiamo facendo un chatbot con watson assistant che sappia rispondere a varie domande sul film Blade Runner. Il chatbot è stato poi interfacciato con Telegram ed è stata aggiunta la possibilità di inviare domande tramite audio che vengono trascritti da DS
* Link video: https://shared02.opsone-cloud.ch/index.php/s/ECixJckZTeeXkKN
* Esperienze in progetti FOSS: Da qualche mese lavoro alle mod del server Minetest di eticadigitale.org (https://gitlab.com/zughy-friends-minetest). Non ho altra esperienza nel mondo foss ma spero di farne molta con il passare del tempo!

Edit: Il bot è ora online all'username: @WatsonAssistantBladeRunnerbot. Non sempre sarà online in quanto continuo ad aggiornarlo ogni giorno ma proverò a tenerlo online il più possibile!

**Comment by Sav22999** [comment]
Grazie per la partecipazione al contest!
L'idea del progetto è molto simpatica e sicuramente utile, oltre ad essere "multi-piattaforma" grazie al fatto che Telegram è supportato ovunque.

**Comment by Sav22999** [comment]
@Anulo2

Il contest è ufficialmente finito ieri. Stiamo valutando i progetti per decretare i vincitori. Ringraziamo, comunque, indistintamente tutti per aver partecipato a questo primo contest di Mozilla Italia su DeepSpeech.
I parametri di valutazione sono i seguenti (lo comunichiamo ora per trasparenza e chiarezza): User-friendly, Estensibilità, Documentazione, Chiarezza del codice, Originalità e Valutazione soggettiva (del singolo giurato).
Quando avremo finito le valutazioni sarà resa pubblica la classifica con la media delle valutazione dei membri della giuria (ed eventualmente una breve motivazione, generale). Sarà resa disponibile anche la spiegazione di ogni singolo parametro.
